name: CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      - name: Pull Required Images
        run: |
          docker-compose -f docker-compose.yml pull

      - name: Deploy Kong Gateway
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AUTHSERVICE_CONNECTIONSTRING: ${{ secrets.AUTHSERVICE_CONNECTIONSTRING }}
          AUTH_DBNAME: ${{ secrets.AUTH_DBNAME }}
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET }}
        run: |
          docker-compose -f docker-compose.yml up -d
