name: CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Build and Push Docker Image for Kong Gateway
      - name: Build and Push Kong Gateway Docker Image
        env:
          APP_UID: 1000
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kong-gateway:latest ./kongconfig
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/kong-gateway:latest


      # Step 4: Pull Required Images for Deployment
      - name: Pull Required Images
        run: |
          docker-compose -f docker-compose.yml pull

      # Step 5: Deploy Kong Gateway and Auth Service
      - name: Deploy Kong Gateway
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AUTHSERVICE_CONNECTIONSTRING: ${{ secrets.AUTHSERVICE_CONNECTIONSTRING }}
          AUTH_DBNAME: ${{ secrets.AUTH_DBNAME }}
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET }}
        run: |
          docker-compose -f docker-compose.yml up -d
